// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:79cebcf3-dd1a-44b0-ae72-3aa9cc6e5586",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_AKcnpEJfl",
    "aws_user_pools_web_client_id": "2mnali4tlvelsr4gev0jgre64u",
    "oauth": {}
};


export default awsmobile;
